### ISSUE TITLE
[오류] 애플 로그인 도중 취소 시 무한 로딩

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#1]
**어떤 오류가 발생했나요?**
발생한 오류를 자세히 적어주세요

애플 로그인 후 표시되는 알럿에서 취소 시 로딩창이 사라지지 않음

**재현 경로**
어떤 경로로 오류가 발생했는지 적어주세요:

로그인 화면 > 애플 로그인 > 취소

**기대 결과**
오류가 발생하지 않았을 시 정상적인 결과를 적어주세요

로딩화면이 사라지며 다른 방법으로 로그인 진행이 가능해야함

**스크린샷**
(가능하다면) 스크린샷을 첨부해주세요
<img src=https://user-images.githubusercontent.com/55052074/202380351-9f99fcac-eebb-47cf-a26c-a175dc40c33b.jpg width=360/>

**기기 정보:**
 - Device: iPad Pro 12.9 3th Generation
 - OS: iPadOS 16.1

**기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
해당 이슈 수정되었습니다. 최신 버전에서 확인 가능합니다.
