### ISSUE TITLE
[제안] SNS 메소드 아이콘 변경 요청

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#13]
**1. 어떤 불편함이 있었나요?**

**AS-IS**
<img width=480 src="https://user-images.githubusercontent.com/55052074/211975329-e875d4cc-2c16-4380-b2b5-eacbc0696e72.jpeg"/>

**TO-BE**
<img src="https://user-images.githubusercontent.com/55052074/211975570-2bfcc91d-5d89-4d93-8d1a-6bf027894ca1.png"/>

**2. 어떤 기능이 추가됐으면 좋겠나요?**
이메일 로그인은 envelop 아이콘, 카카오 로그인은 카카오 말풍선, 구글 로그인은 구글 로고가 dim300 Color로 들어가야합니다.

**3. 기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
차기버전 반영예정
