### ISSUE TITLE
[제안] 메인화면 목록/지도 토글버튼 간격 수정

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#14]
**1. 어떤 불편함이 있었나요?**
<img width=360 src="https://user-images.githubusercontent.com/55052074/211976617-e286722f-229a-4c13-8925-e94b75016bcc.jpeg"/> <img width=360 src="https://user-images.githubusercontent.com/55052074/211976709-8a5509b1-1bec-4b66-915d-64e75b2d6ea8.jpeg"/>

**2. 어떤 기능이 추가됐으면 좋겠나요?**
각 화면에서 간격이 장소 버튼 기준으로 일치했으면 좋겠습니다.

**3. 기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
차기버전 반영예정
