### ISSUE TITLE
[제안] 지도/리스트 전환 버튼 간격

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#2]
**어떤 불편함이 있었나요?**
<img src=https://user-images.githubusercontent.com/55052074/202380931-9dd7d358-8fbc-467a-9b10-8d58c78029ec.PNG width=360/>

지도에서 리스트로 돌아가는 버튼 상단에 간격이 없어 어색한 것 같습니다.

**어떤 기능이 추가됐으면 좋겠나요?**

상단에 간격이 존재하면 좋겠습니다.

**기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
해당 이슈 수정되었습니다. 최신 버전에서 확인 가능합니다
