### ISSUE TITLE
[오류] 상단 기본이미지 다름

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#3]
**1. 어떤 오류가 발생했나요?**
발생한 오류를 자세히 적어주세요

상단 이미지가 디자인과 다릅니다.

**2. 재현 경로**
어떤 경로로 오류가 발생했는지 적어주세요:

**3. 기대 결과**
오류가 발생하지 않았을 시 정상적인 결과를 적어주세요
<img src=https://user-images.githubusercontent.com/55052074/202895915-f2c34384-3dec-4f2f-b09c-f3b0b4bd3bb7.jpeg width=360/>

**4. 스크린샷**
(가능하다면) 스크린샷을 첨부해주세요
<img src=https://user-images.githubusercontent.com/55052074/202895910-30209fc2-d38c-4486-85c8-c9c75f402dd3.jpeg width=360/>

**5. 기기 정보**
 - Device: iPad 12.9 3th gen
 - OS: iPad OS 16

**6. 기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
해당 이슈 수정되었습니다. 최신 버전에서 확인 가능합니다
