### ISSUE TITLE
[제안] 매장 목록 표시 순서 다름

### ISSUE THREAD

**Issue by jsb408** [STUDIO-EXYT/TIPXY-report#4]
**1. 어떤 불편함이 있었나요?**
**iOS**
<img src=https://user-images.githubusercontent.com/55052074/202895989-786d1bd8-d319-4cb7-8d89-6ceb19103dc5.jpeg width=360/>
**Android**
<img src=https://user-images.githubusercontent.com/55052074/202895994-969c3751-cd2e-44b3-a4c5-777ed8e7b28b.jpeg width=360/>

**2. 어떤 기능이 추가됐으면 좋겠나요?**
표시되고 있는 매장 순서가 다른데 통일해야할 것 같습니다!

**3. 기타**
추가적으로 적어주실 말씀이 있다면 적어주세요.

**Comment by kgun90** [comment]
해당 이슈 수정되었습니다. 최신 버전에서 확인 가능합니다
